ALTER TABLE `users` ADD COLUMN `rating` INT DEFAULT 0;
ALTER TABLE `users` ADD COLUMN `daily_rating` INT DEFAULT 1;

CREATE TABLE IF NOT EXISTS `comments` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Comment` varchar(225) NOT NULL,
  `SendTo` int(11) NOT NULL,
  `SentFrom` varchar(150) NOT NULL,
  `SentOn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
